# **Default Setting**

* Python: 3.6.9
* ML Framework: tf-nightly-gpu 2.5.0-dev20201208
* CPU: AMD Ryzen 5 5600X 6-Core Processor
* GPU: GeForce RTX 3070 (8G) (CUDA 11.1)
* RAM: 32G
* Platform: linux 20.04 LTS

In [1]:
%env NOTEBOOKNAME try3
%env LOCAL_DATA_PATH data
%env SUBMISSION_PATH submission

env: NOTEBOOKNAME=try3
env: LOCAL_DATA_PATH=data
env: SUBMISSION_PATH=submission

In [2]:
import tensorflow as tf
import tensorflow_addons as tfa

import datetime
import glob
import os
import platform

import numpy as np
import pandas as pd

from collections import OrderedDict
from sklearn.model_selection import train_test_split

print(f"tf.__version__: {tf.__version__}")
print(f"tfa.__version__: {tfa.__version__}")

tf.__version__: 2.5.0-dev20201208
tfa.__version__: 0.11.2

/home/myunggyo/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_addons/utils/ensure_tf_install.py:44: UserWarning: You are currently using a nightly version of TensorFlow (2.5.0-dev20201208).
TensorFlow Addons offers no support for the nightly versions of TensorFlow. Some things might work, some other might not.
If you encounter a bug, do not file an issue on GitHub.
  UserWarning,

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!python -V

Python 3.6.9 :: Anaconda, Inc.

In [5]:
# !cat /proc/cpuinfo

In [6]:
!nvidia-smi

Thu Dec 10 23:02:24 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Graphics Device     On   | 00000000:0A:00.0  On |                  N/A |
|  0%   34C    P8    24W / 220W |    295MiB /  7979MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       889      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      7713      G   /usr/lib/xorg/Xorg                 88MiB |
|    0   N/A  N/A      7838      G   /usr/bin/gnome-shell               24MiB |
|    0   N/A  N/A      8849      G   ...AAAAAAAA== --shared-files      128MiB |
+-----------------------------------------------------------------------------+

In [7]:
# !df -h

In [8]:
!free -h

              total        used        free      shared  buff/cache   available
Mem:           31Gi       2.9Gi        25Gi       438Mi       3.2Gi        27Gi
Swap:         2.0Gi          0B       2.0Gi

In [9]:
platform.platform()

'Linux-5.4.0-56-generic-x86_64-with-debian-bullseye-sid'

In [10]:
# Load the TensorBoard notebook extension.
%load_ext tensorboard

# **Define Arguments**

In [28]:
args = OrderedDict({
    # Basic
    "SEED": 42,
    "TEST_SIZE": 0.2,
    "EPOCH": 10,
    "INIT_LR": 1e-3,
    
    # Dataframe
    "NUM_TEST_CSV": 81,
    
    # Dataset Pipeline
    "WINDOW_INP": 7 * 24 * 2, # 336, 7 days
    "WINDOW_TAR": 2 * 24 * 2, # 96, 2 days
    "WINDOW_SHIFT": 1 * 24 * 2, # 1 day
    "WINDOW_STRIDE": 1,
    "WINDOW_DR": True, # Drop remainders
    "AUTO": tf.data.experimental.AUTOTUNE,
    
    "GLOBAL_BATCH_SIZE": 128,
    
    # Model
    "NUM_UNITS": 32, # lstm units
    "NUM_FEATURES": 6, # dense featues
    "NUM_QUANTILE": 9,
    
})

args

OrderedDict([('SEED', 42),
             ('TEST_SIZE', 0.2),
             ('EPOCH', 10),
             ('INIT_LR', 0.001),
             ('NUM_TEST_CSV', 81),
             ('WINDOW_INP', 336),
             ('WINDOW_TAR', 96),
             ('WINDOW_SHIFT', 48),
             ('WINDOW_STRIDE', 1),
             ('WINDOW_DR', True),
             ('AUTO', -1),
             ('GLOBAL_BATCH_SIZE', 128),
             ('NUM_UNITS', 32),
             ('NUM_FEATURES', 6),
             ('NUM_QUANTILE', 9)])

# **Load Datasets**

## **Train / Validation**

In [12]:
df = pd.read_csv(os.path.join(os.environ["LOCAL_DATA_PATH"], "train", "train.csv"))
df.head()

   Day  Hour  Minute  DHI  DNI   WS     RH   T  TARGET
0    0     0       0    0    0  1.5  69.08 -12     0.0
1    0     0      30    0    0  1.5  69.06 -12     0.0
2    0     1       0    0    0  1.6  71.78 -12     0.0
3    0     1      30    0    0  1.6  71.75 -12     0.0
4    0     2       0    0    0  1.6  75.20 -12     0.0

In [13]:
df.describe()

,Day,Hour,Minute,DHI,DNI,WS,RH,T,TARGET
count,52560.000000,52560.000000,52560.000000,52560.000000,52560.000000,52560.000000,52560.000000,52560.000000,52560.000000
mean,547.000000,11.500000,15.000000,64.344121,234.792371,2.456033,56.793102,9.279928,17.790630
std,316.102148,6.922252,15.000143,103.897125,349.684583,1.426874,22.052875,10.179741,25.759955
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.590000,-19.000000,0.000000
25%,273.000000,5.750000,0.000000,0.000000,0.000000,1.400000,39.697500,1.000000,0.000000
50%,547.000000,11.500000,15.000000,0.000000,0.000000,2.200000,57.600000,9.000000,0.000000
75%,821.000000,17.250000,30.000000,87.000000,469.000000,3.200000,72.770000,17.000000,32.089890
max,1094.000000,23.000000,30.000000,528.000000,1059.000000,12.000000,100.000000,35.000000,99.913939

In [14]:
tr_df, vl_df = train_test_split(
    df, 
    test_size = args["TEST_SIZE"], 
    random_state = args["SEED"])

tr_df.shape, vl_df.shape

((42048, 9), (10512, 9))

In [15]:
def preprocessing(df, is_training = True):
    # Drop timestampes.
    try:
        df = df.drop(["Day", "Hour", "Minute"], axis = 1)
    except:
        pass
    
    # Normalize.
    for column in df.columns:
        if is_training:
            args[f"{column}_MAX"] = df[column].max()
            args[f"{column}_MIN"] = df[column].min()
        
        df[column] = (df[column] - args[f"{column}_MIN"]) / (args[f"{column}_MAX"] - args[f"{column}_MIN"])
        
    return df

In [16]:
tr_df = preprocessing(tr_df)
vl_df = preprocessing(vl_df, is_training = False)

In [17]:
tr_df.describe()

,DHI,DNI,WS,RH,T,TARGET
count,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000
mean,0.121155,0.221624,0.204474,0.532615,0.523211,0.177645
std,0.195675,0.330325,0.118662,0.238854,0.188508,0.257436
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.116667,0.347040,0.370370,0.000000
50%,0.000000,0.000000,0.183333,0.541392,0.518519,0.000000
75%,0.164773,0.443815,0.266667,0.706309,0.666667,0.320789
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
vl_df.describe()

,DHI,DNI,WS,RH,T,TARGET
count,10512.000000,10512.000000,10512.000000,10512.000000,10512.000000,10512.000000
mean,0.124701,0.222062,0.205452,0.531757,0.525669,0.181208
std,0.201099,0.329730,0.119881,0.237798,0.188532,0.261486
min,0.000000,0.000000,0.008333,0.004437,0.037037,0.000000
25%,0.000000,0.000000,0.116667,0.348231,0.370370,0.000000
50%,0.000000,0.000000,0.183333,0.540634,0.518519,0.000000
75%,0.168561,0.438149,0.266667,0.700249,0.666667,0.324526
max,0.990530,0.998111,0.983333,1.000000,1.000000,1.001672

## **Test**

In [19]:
ts_filenames = [os.path.join(os.environ["LOCAL_DATA_PATH"], "test", f"{i}.csv") for i in range(args["NUM_TEST_CSV"])]
ts_dfs = [preprocessing(pd.read_csv(ts_filename), is_training = False) for ts_filename in ts_filenames]
ts_df = pd.concat(ts_dfs)

In [20]:
ts_df.head()

   DHI  DNI        WS        RH         T  TARGET
0  0.0  0.0  0.225000  0.290337  0.351852     0.0
1  0.0  0.0  0.225000  0.287631  0.353704     0.0
2  0.0  0.0  0.225000  0.288280  0.355556     0.0
3  0.0  0.0  0.225000  0.285683  0.357407     0.0
4  0.0  0.0  0.233333  0.285467  0.359259     0.0

In [21]:
ts_df.describe()

,DHI,DNI,WS,RH,T,TARGET
count,27216.000000,27216.000000,27216.000000,27216.000000,27216.000000,27216.000000
mean,0.111880,0.237133,0.189333,0.419916,0.532339,0.182813
std,0.173494,0.338179,0.105967,0.207518,0.209003,0.261818
min,0.000000,0.000000,0.008333,-0.029001,0.061111,0.000000
25%,0.000000,0.000000,0.108333,0.254166,0.359259,0.000000
50%,0.011364,0.000000,0.166667,0.424629,0.512963,0.005645
75%,0.157197,0.477809,0.241667,0.576669,0.690741,0.326398
max,0.960227,1.018886,0.916667,0.919597,1.031481,0.997030

# **Make Dataset Pipelines**

In [22]:
@tf.function
def _flat_fn_tr(x):
    return x.batch(args["WINDOW_INP"] + args["WINDOW_TAR"])


@tf.function
def _flat_fn_ts(x):
    return x.batch(args["WINDOW_INP"])


@tf.function
def _split_window(features):
    return tf.split(features, [args["WINDOW_INP"], args["WINDOW_TAR"]], axis = 0)

In [23]:
tr_tensor = tf.constant(tr_df, dtype = tf.float32)
vl_tensor = tf.constant(vl_df, dtype = tf.float32)
ts_tensor = tf.constant(ts_df, dtype = tf.float32)

tr_dataset = tf.data.Dataset.from_tensor_slices(tr_tensor
                    ).window(args["WINDOW_INP"] + args["WINDOW_TAR"], args["WINDOW_SHIFT"], args["WINDOW_STRIDE"], args["WINDOW_DR"]).flat_map(_flat_fn_tr
                    ).map(_split_window, num_parallel_calls = args["AUTO"]
                    ).batch(args["GLOBAL_BATCH_SIZE"]
                    ).cache(
                    ).prefetch(args["AUTO"])

vl_dataset = tf.data.Dataset.from_tensor_slices(vl_tensor
                    ).window(args["WINDOW_INP"] + args["WINDOW_TAR"], args["WINDOW_SHIFT"], args["WINDOW_STRIDE"], args["WINDOW_DR"]).flat_map(_flat_fn_tr
                    ).map(_split_window, num_parallel_calls = args["AUTO"]
                    ).batch(args["GLOBAL_BATCH_SIZE"]
                    ).cache(
                    ).prefetch(args["AUTO"])

ts_dataset = tf.data.Dataset.from_tensor_slices(ts_tensor
                    ).window(args["WINDOW_INP"], args["WINDOW_INP"], args["WINDOW_STRIDE"], args["WINDOW_DR"]).flat_map(_flat_fn_ts
#                     ).map(_split_window, num_parallel_calls = args["AUTO"]
                    ).batch(args["NUM_TEST_CSV"] # Not args["GLOBAL_BATCH_SIZE"]
#                     ).cache(
                    ).prefetch(args["AUTO"])

# Print the shapes
print(f"tr_dataset: {tr_dataset.element_spec}")
print(f"vl_dataset: {vl_dataset.element_spec}")
print(f"ts_dataset: {ts_dataset.element_spec}")

tr_dataset: (TensorSpec(shape=(None, 336, 6), dtype=tf.float32, name=None), TensorSpec(shape=(None, 96, 6), dtype=tf.float32, name=None))
vl_dataset: (TensorSpec(shape=(None, 336, 6), dtype=tf.float32, name=None), TensorSpec(shape=(None, 96, 6), dtype=tf.float32, name=None))
ts_dataset: TensorSpec(shape=(None, None, 6), dtype=tf.float32, name=None)

## **Take Samples**

In [24]:
for element in tr_dataset.take(1):
    foo, bar = element
    print(foo.shape, bar.shape)

(128, 336, 6) (128, 96, 6)

In [25]:
for element in vl_dataset.take(1):
    foo, bar = element
    print(foo.shape, bar.shape)

(128, 336, 6) (128, 96, 6)

In [26]:
for element in ts_dataset.take(1):
    foo = element
    print(foo.shape)

(81, 336, 6)

# **Create Network**

In [38]:
class AR_LSTM(tf.keras.Model):
    def __init__(self, units, out_steps, name):
        super(AR_LSTM, self).__init__(name = name)
        self.units = units
        self.out_steps = out_steps
        self.num_features = args["NUM_FEATURES"]
        
        self.lstm_cell = tf.keras.layers.LSTMCell(self.units)
        self.lstm_rnn = tf.keras.layers.RNN(self.lstm_cell, return_state = True)
        self.dense = tf.keras.layers.Dense(self.num_features)
        
    
    def warmup(self, inputs):
        x, *state = self.lstm_rnn(inputs)
        prediction = self.dense(x)
        return prediction, state
        
        
    def call(self, inputs, training = None):
        predictions = []
        
        prediction, state = self.warmup(inputs)
        predictions.append(prediction)
        
        for n in range(1, self.out_steps):
            x = prediction
            x, state = self.lstm_cell(x, states = state, training = training)
            prediction = self.dense(x)
            predictions.append(prediction)
            
        predictions = tf.stack(predictions, axis = 1)
        return predictions

# **Compile and Fit**

   * Repeat the last 24 hours.

In [51]:
models = []

for tau in np.arange(0.1, 1, 0.1):
    model = AR_LSTM(
        units = args["NUM_UNITS"], 
        out_steps = args["WINDOW_TAR"],
        name = f"P{tau:.1f}")

    model.compile(
        loss = tfa.losses.PinballLoss(tau = tau),
        optimizer = tf.keras.optimizers.Adam(args["INIT_LR"]))
    
    models.append(model)

In [53]:
for model in models:
    # TensorBoard callback.
    log_dir = os.path.join(
        "logs", "fit", os.environ["NOTEBOOKNAME"], 
        datetime.datetime.now().strftime(f"{model.name}-%Y%m%d-%H%M%S"))
    tb_callback = tf.keras.callbacks.TensorBoard(log_dir = log_dir, histogram_freq = 1)

    print(f"\nModel {model.name}...\n")
    
    _ = model.fit(
        tr_dataset,
        validation_data = vl_dataset,
        epochs = args["EPOCH"],
        verbose = 2,
        callbacks = [tb_callback])

Model P0.1...

Epoch 1/10
7/7 - 12s - loss: 0.0296 - val_loss: 0.0288
Epoch 2/10
7/7 - 1s - loss: 0.0280 - val_loss: 0.0273
Epoch 3/10
7/7 - 1s - loss: 0.0266 - val_loss: 0.0262
Epoch 4/10
7/7 - 1s - loss: 0.0255 - val_loss: 0.0251
Epoch 5/10
7/7 - 1s - loss: 0.0245 - val_loss: 0.0242
Epoch 6/10
7/7 - 1s - loss: 0.0237 - val_loss: 0.0236
Epoch 7/10
7/7 - 1s - loss: 0.0233 - val_loss: 0.0235
Epoch 8/10
7/7 - 1s - loss: 0.0232 - val_loss: 0.0235
Epoch 9/10
7/7 - 1s - loss: 0.0232 - val_loss: 0.0232
Epoch 10/10
7/7 - 1s - loss: 0.0231 - val_loss: 0.0232

Model P0.2...

Epoch 1/10
7/7 - 14s - loss: 0.0580 - val_loss: 0.0554
Epoch 2/10
7/7 - 1s - loss: 0.0526 - val_loss: 0.0489
Epoch 3/10
7/7 - 1s - loss: 0.0470 - val_loss: 0.0454
Epoch 4/10
7/7 - 1s - loss: 0.0436 - val_loss: 0.0427
Epoch 5/10
7/7 - 1s - loss: 0.0422 - val_loss: 0.0426
Epoch 6/10
7/7 - 1s - loss: 0.0421 - val_loss: 0.0421
Epoch 7/10
7/7 - 1s - loss: 0.0418 - val_loss: 0.0422
Epoch 8/10
7/7 - 1s - loss: 0.0417 - val_loss: 0.0419
Epoch 9/10
7/7 - 1s - loss: 0.0416 - val_loss: 0.0420
Epoch 10/10
7/7 - 1s - loss: 0.0416 - val_loss: 0.0418

Model P0.3...

Epoch 1/10
7/7 - 11s - loss: 0.0891 - val_loss: 0.0878
Epoch 2/10
7/7 - 1s - loss: 0.0859 - val_loss: 0.0840
Epoch 3/10
7/7 - 1s - loss: 0.0814 - val_loss: 0.0781
Epoch 4/10
7/7 - 1s - loss: 0.0737 - val_loss: 0.0680
Epoch 5/10
7/7 - 1s - loss: 0.0641 - val_loss: 0.0597
Epoch 6/10
7/7 - 1s - loss: 0.0589 - val_loss: 0.0595
Epoch 7/10
7/7 - 1s - loss: 0.0588 - val_loss: 0.0585
Epoch 8/10
7/7 - 1s - loss: 0.0578 - val_loss: 0.0580
Epoch 9/10
7/7 - 1s - loss: 0.0577 - val_loss: 0.0579
Epoch 10/10
7/7 - 1s - loss: 0.0576 - val_loss: 0.0578

Model P0.4...

Epoch 1/10
7/7 - 11s - loss: 0.1144 - val_loss: 0.1058
Epoch 2/10
7/7 - 1s - loss: 0.0989 - val_loss: 0.0898
Epoch 3/10
7/7 - 1s - loss: 0.0808 - val_loss: 0.0734
Epoch 4/10
7/7 - 1s - loss: 0.0742 - val_loss: 0.0740
Epoch 5/10
7/7 - 1s - loss: 0.0725 - val_loss: 0.0719
Epoch 6/10
7/7 - 1s - loss: 0.0714 - val_loss: 0.0715
Epoch 7/10
7/7 - 1s - loss: 0.0711 - val_loss: 0.0711
Epoch 8/10
7/7 - 1s - loss: 0.0708 - val_loss: 0.0713
Epoch 9/10
7/7 - 1s - loss: 0.0708 - val_loss: 0.0712
Epoch 10/10
7/7 - 1s - loss: 0.0706 - val_loss: 0.0710

Model P0.5...

Epoch 1/10
7/7 - 11s - loss: 0.1457 - val_loss: 0.1386
Epoch 2/10
7/7 - 2s - loss: 0.1279 - val_loss: 0.1062
Epoch 3/10
7/7 - 1s - loss: 0.0922 - val_loss: 0.0841
Epoch 4/10
7/7 - 1s - loss: 0.0842 - val_loss: 0.0841
Epoch 5/10
7/7 - 1s - loss: 0.0822 - val_loss: 0.0829
Epoch 6/10
7/7 - 1s - loss: 0.0818 - val_loss: 0.0819
Epoch 7/10
7/7 - 1s - loss: 0.0813 - val_loss: 0.0815
Epoch 8/10
7/7 - 1s - loss: 0.0811 - val_loss: 0.0816
Epoch 9/10
7/7 - 1s - loss: 0.0810 - val_loss: 0.0815
Epoch 10/10
7/7 - 1s - loss: 0.0810 - val_loss: 0.0815

Model P0.6...

Epoch 1/10
7/7 - 11s - loss: 0.1677 - val_loss: 0.1463
Epoch 2/10
7/7 - 1s - loss: 0.1257 - val_loss: 0.1151
Epoch 3/10
7/7 - 1s - loss: 0.1053 - val_loss: 0.0997
Epoch 4/10
7/7 - 1s - loss: 0.0940 - val_loss: 0.0907
Epoch 5/10
7/7 - 1s - loss: 0.0889 - val_loss: 0.0884
Epoch 6/10
7/7 - 1s - loss: 0.0876 - val_loss: 0.0884
Epoch 7/10
7/7 - 1s - loss: 0.0876 - val_loss: 0.0880
Epoch 8/10
7/7 - 1s - loss: 0.0872 - val_loss: 0.0877
Epoch 9/10
7/7 - 1s - loss: 0.0871 - val_loss: 0.0876
Epoch 10/10
7/7 - 1s - loss: 0.0870 - val_loss: 0.0876

Model P0.7...

Epoch 1/10
7/7 - 11s - loss: 0.2016 - val_loss: 0.1913
Epoch 2/10
7/7 - 1s - loss: 0.1771 - val_loss: 0.1505
Epoch 3/10
7/7 - 1s - loss: 0.1249 - val_loss: 0.1053
Epoch 4/10
7/7 - 1s - loss: 0.0948 - val_loss: 0.0916
Epoch 5/10
7/7 - 1s - loss: 0.0894 - val_loss: 0.0889
Epoch 6/10
7/7 - 1s - loss: 0.0872 - val_loss: 0.0865
Epoch 7/10
7/7 - 1s - loss: 0.0862 - val_loss: 0.0863
Epoch 8/10
7/7 - 1s - loss: 0.0859 - val_loss: 0.0861
Epoch 9/10
7/7 - 1s - loss: 0.0856 - val_loss: 0.0861
Epoch 10/10
7/7 - 1s - loss: 0.0856 - val_loss: 0.0860

Model P0.8...

Epoch 1/10
7/7 - 11s - loss: 0.2295 - val_loss: 0.2152
Epoch 2/10
7/7 - 1s - loss: 0.1909 - val_loss: 0.1421
Epoch 3/10
7/7 - 1s - loss: 0.1223 - val_loss: 0.1116
Epoch 4/10
7/7 - 1s - loss: 0.1005 - val_loss: 0.0884
Epoch 5/10
7/7 - 1s - loss: 0.0843 - val_loss: 0.0775
Epoch 6/10
7/7 - 1s - loss: 0.0758 - val_loss: 0.0740
Epoch 7/10
7/7 - 1s - loss: 0.0736 - val_loss: 0.0742
Epoch 8/10
7/7 - 1s - loss: 0.0734 - val_loss: 0.0738
Epoch 9/10
7/7 - 1s - loss: 0.0728 - val_loss: 0.0732
Epoch 10/10
7/7 - 1s - loss: 0.0725 - val_loss: 0.0731

Model P0.9...

Epoch 1/10
7/7 - 11s - loss: 0.2604 - val_loss: 0.2442
Epoch 2/10
7/7 - 1s - loss: 0.2203 - val_loss: 0.1832
Epoch 3/10
7/7 - 1s - loss: 0.1539 - val_loss: 0.1168
Epoch 4/10
7/7 - 1s - loss: 0.0901 - val_loss: 0.0671
Epoch 5/10
7/7 - 1s - loss: 0.0612 - val_loss: 0.0572
Epoch 6/10
7/7 - 1s - loss: 0.0541 - val_loss: 0.0512
Epoch 7/10
7/7 - 1s - loss: 0.0487 - val_loss: 0.0471
Epoch 8/10
7/7 - 1s - loss: 0.0466 - val_loss: 0.0472
Epoch 9/10
7/7 - 1s - loss: 0.0465 - val_loss: 0.0468
Epoch 10/10
7/7 - 1s - loss: 0.0464 - val_loss: 0.0465

In [54]:
%tensorboard --logdir logs/fit --host jupyter-server

Reusing TensorBoard on port 6006 (pid 20358), started 1:09:08 ago. (Use '!kill 20358' to kill it.)

# **Predict**

In [55]:
preds = [np.array(model.predict(ts_dataset))[..., -1] for model in models]
preds[0].shape

WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f6f569f58c8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 15 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f6f5445e840> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 16 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f6f5447d620> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 17 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f6f4ba33f28> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 18 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f6f4ad12598> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 19 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f6f4a6e3598> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

(81, 96)

In [56]:
submission = pd.read_csv(os.path.join(os.environ["LOCAL_DATA_PATH"], "sample_submission.csv"), index_col = "id")
submission.head()

,q_0.1,q_0.2,q_0.3,q_0.4,q_0.5,q_0.6,q_0.7,q_0.8,q_0.9
id,,,,,,,,,
0.csv_Day7_0h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.csv_Day7_0h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.csv_Day7_1h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.csv_Day7_1h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.csv_Day7_2h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
for i, column in enumerate(submission.columns):
    submission[column] = np.reshape(preds[i], (-1,))

In [58]:
submission.head()

,q_0.1,q_0.2,q_0.3,q_0.4,q_0.5,q_0.6,q_0.7,q_0.8,q_0.9
id,,,,,,,,,
0.csv_Day7_0h00m,-0.111187,-0.041373,0.008617,-0.059796,0.004900,0.091378,0.172685,0.323725,0.449764
0.csv_Day7_0h30m,-0.081781,-0.023991,0.007219,-0.047256,0.003484,0.083848,0.174555,0.317999,0.526369
0.csv_Day7_1h00m,-0.059005,-0.010888,0.005695,-0.036513,0.002933,0.085585,0.178056,0.320249,0.553838
0.csv_Day7_1h30m,-0.041658,-0.001896,0.004918,-0.028249,0.002503,0.088325,0.182170,0.323299,0.576840
0.csv_Day7_2h00m,-0.028830,0.003767,0.004728,-0.021873,0.002575,0.091377,0.186195,0.326818,0.595288

In [59]:
submission.to_csv(
    os.path.join(os.environ["SUBMISSION_PATH"], f"{os.environ['NOTEBOOKNAME']}_submission.csv"))